# -*- coding: utf-8 -*-
"""ChessCUDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQ0TktluWsYtDxDU8Iz9mF2SZECdSBGF
"""

!nvidia-smi

!git clone https://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@github.com/mresidovic1/cuda-mc-chess-engine.git

cd cuda-mc-chess-engine

!git checkout monte-carlo-v1-test

cd gpu

!git pull origin monte-carlo-v1-test

!chmod +x build.sh

!./build.sh

!./monte_carlo_advanced 50000 "5r2/Rpp4p/3k2p1/3N4/2P1P1b1/1PQ3P1/1P5r/4KB1q w - - 0 1"

!apt-get update
!apt-get install -y cuda-toolkit-11-8

!git fetch

!git checkout monte-carlo-v3

!ls src/
!ls tests/

!nvcc -std=c++17 -Iinclude tests/test_runner.cpp src/gpu_kernels.cu src/init_tables.cu src/mcts.cpp -o test_runner

!nvcc -std=c++17 -arch=sm_75 -Iinclude tests/test_runner.cpp src/gpu_kernels.cu src/init_tables.cu src/mcts.cpp -o test_runner

!./test_runner --all

!git pull origin monte-carlo-v3

!nvcc -std=c++17 -arch=sm_75 -Iinclude tests/test_runner.cpp src/gpu_kernels.cu src/init_tables.cu src/mcts.cpp -o test_runner

!./test_runner --all

!git fetch

!git checkout monte-carlo-v3-sejtanluci

!git pull origin monte-carlo-v3-sejtanluci

!nvcc -std=c++17 -arch=sm_75 -Iinclude tests/test_runner.cpp src/gpu_kernels.cu src/init_tables.cu src/mcts.cpp -o test_runner

!./test_runner --all